[build]
builder = "NIXPACKS"
buildCommand = "corepack enable && pnpm install --frozen-lockfile && pnpm --filter @club-website/public-website... build"

[deploy]
startCommand = "pnpm --filter @club-website/public-website... start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }
